config {
    folder = ${CONFIG_FILE_FOLDER}
    masterPassword = ${SERVER_MASTER_KEY}
    serverName = ${SERVER_NAME}
    interfaces = ${INTERFACES_NAMES}
    networkInterfaceOverride = ${?NETWORK_INTERFACE_OVERRIDE}
}